// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTFrxbkMhOqdleFnqdB9Uv9Nr7OF2LSo',
    appId: '1:608096145858:web:82b9173046fb217ec5065b',
    messagingSenderId: '608096145858',
    projectId: 'dailyplanner-4b922',
    authDomain: 'dailyplanner-4b922.firebaseapp.com',
    databaseURL: 'https://dailyplanner-4b922-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyplanner-4b922.firebasestorage.app',
    measurementId: 'G-RFJ3BMM5SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmV00adRZgSFpJLDYgLpZAHPm7pvaPDVA',
    appId: '1:608096145858:android:4e32917d31578478c5065b',
    messagingSenderId: '608096145858',
    projectId: 'dailyplanner-4b922',
    databaseURL: 'https://dailyplanner-4b922-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyplanner-4b922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlxg2e9a-MokYFtA6_EdyIILye9SLvoc',
    appId: '1:608096145858:ios:deca587e8b4cd664c5065b',
    messagingSenderId: '608096145858',
    projectId: 'dailyplanner-4b922',
    databaseURL: 'https://dailyplanner-4b922-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dailyplanner-4b922.firebasestorage.app',
    iosClientId: '608096145858-iqrkj7q5idggu5eo1nngrq6am5toqi25.apps.googleusercontent.com',
    iosBundleId: 'com.example.routine',
  );
}
